### ISSUE TITLE
We need to edit the section of "Before you begin" since we have 2 types of volume copy

### ISSUE THREAD

**Issue by ookootoo** [NetAppDocs/e-series-santricity#14]
### Page URL

https://docs.netapp.com/us-en/e-series-santricity/sm-storage/copy-volume.html

### Page title

Copy volume

### Summary

Since we have 2 different types of volume copy (online VS offline), we need to clearly write down the section of "Before you begin" separately. It seems to me the current "Before you begin" is only targeted to "offline volume copy". Against the "online volume copy" , based on my experience, we don't need to stop I/O and unmount volume. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Thank you so much for your feedback. We will review this item and update the accordingly. We will keep you posted once the updated documentation is available. 

Thanks again for you help, 

Don Riley

**Comment by netapp-driley** [comment]
After talking with E-Series engineering, I was able to confirm the "Before you begin" steps apply to both offline and online copy types.
