### ISSUE TITLE
Text in instructions doesn't correspond to the UI

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/e-series-santricity#15]
### Page URL

https://docs.netapp.com/us-en/e-series-santricity/sm-hardware/configure-iser-over-infiniband-ports-hardware.html

### Page title

Configure iSER over InfiniBand ports

### Summary

> Select Hardware.
> If the graphic shows the drives, click Show back of shelf.

![image](https://github.com/NetAppDocs/e-series-santricity/assets/16622642/2ea8b9b2-93ac-4af1-8143-b89909314f06)

Where is this "Show back of shelf"?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Thank you so much for your feedback. We'll review this item and update the documentation accordingly. We'll keep you posted once the updated documentation is available. If you have any other feedback, please let us know. 

Thanks again, 

Don Riley

**Comment by netapp-driley** [comment]
This issue will be corrected in the upcoming SANtricity release.
