### ISSUE TITLE
Is 8TB the correct max?

### ISSUE THREAD

**Issue by ahmadm-netapp** [NetAppDocs/e-series-santricity#16]
### Page URL

https://docs.netapp.com/us-en/e-series-santricity/sm-storage/ssd-cache-restrictions.html

### Page title

SSD Cache restrictions

### Summary

From AadWeb in engineering domain, the limit is 10TB. Can you confirm and update document if it is indeed 10TB.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by scaleoutsean** [comment]
I noticed this just now, after creating #18. Why is this still unresolved?

**Comment by netapp-driley** [comment]
This issue will be corrected in the upcoming SANtricity release.
