### ISSUE TITLE
Wrong information about SSD cache

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/e-series-santricity#18]
### Page URL

https://docs.netapp.com/us-en/e-series-santricity/sm-storage/ssd-cache-restrictions.html

### Page title

SSD Cache restrictions

### Summary

> The maximum usable SSD Cache capacity on a storage array is 8 TB.

It's not, it's *up to* 8 TB. 

This should be fixed by adding a table with the correct information, or by adding "up to" in front of 8 TB. There's a KB [1] on this, but it too doesn't have that information so currently I wouldn't really recommend anyone referring to it either.

![image](https://github.com/NetAppDocs/e-series-santricity/assets/16622642/0e4fc14f-8ed4-4190-8c22-eff491668040)

[1] https://kb.netapp.com/onprem/E-Series/SANtricity_OS/What_is_the_maximum_configurable_SSD_cache_size_on_E_Series_storage_systems

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Hi, 

Thank you so much for your feedback. We will review this item and update the documentation accordingly. If you have any other feedback, please let us know. 

Thanks again, 

Don Riley

**Comment by netapp-driley** [comment]
This issue will be corrected in the upcoming SANtricity release.
