### ISSUE TITLE
Incorrect Link on Synchronous Mirroring Overview

### ISSUE THREAD

**Issue by chjones45** [NetAppDocs/e-series-santricity#2]
Page: [Synchronous mirroring overview](https://docs.netapp.com/us-en/e-series-santricity/sm-mirroring/overview-mirroring-sync.html)

Under the "What is Synchronous Mirroring?" heading, there a section to Learn More. The first link is to "How synchronous mirroring works". The link goes to https://docs.netapp.com/us-en/e-series-santricity/sm-mirroring/how-asynchronous-mirroring-works.html, which is for Asynchronous Mirroring.

The link should go to: https://docs.netapp.com/us-en/e-series-santricity/sm-mirroring/how-synchronous-mirroring-works.html

**Comment by netapp-jsnyder** [comment]
@chjones45 thanks for catching this. We've corrected the link.
