### ISSUE TITLE
Hyperlink for "Change or add host protocols" not working

### ISSUE THREAD

**Issue by alonsod-netapp** [NetAppDocs/e-series-santricity#20]
### Page URL

https://docs.netapp.com/us-en/e-series-santricity/early-versions.html

### Page title

Earlier versions

### Summary

The hyperlink for "Change or add host protocols" doesn't seem to be working.

Looking for instructions to change host protocol for E2700 controller.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Thank you so much for your feedback. We'll investigate this issue and update the documentation accordingly.

**Comment by netapp-driley** [comment]
The broken link appears to be the same file as the following link: https://library.netapp.com/ecm/ecm_download_file/ECMLP2353447

Submitted a service desk ticket to resolve the broken link. 

Provided the [new link](https://library.netapp.com/ecm/ecm_download_file/ECMLP2353447) to the submitter.
