### ISSUE TITLE
Queries regarding the workload description on doc

### ISSUE THREAD

**Issue by zhuolin-shen** [NetAppDocs/e-series-santricity#21]
### Page URL

https://docs.netapp.com/us-en/e-series-santricity/sm-storage/create-workloads.html

### Page title

Create workloads

### Summary

1) What is the reason for below? 
_https://docs.netapp.com/us-en/e-series-santricity/sm-storage/create-workloads.html
System Manager recommends an optimized volume configuration only for the following application types:
•	Microsoft® SQL Server™
•	Microsoft® Exchange Server™
•	Video Surveillance
•	VMware ESXi ™ (for volumes to be used with Virtual Machine File System)_

System manager GUI has predefined and provided many other selections for other application workload
I don't see any reason for this recommends.
![Screenshot 2024-06-14 181201](https://github.com/NetAppDocs/e-series-santricity/assets/112918662/8c6b050d-6f0a-450c-aecb-041e4561c01f)

2) What is the exact difference for these application workload options?
_https://docs.netapp.com/us-en/e-series-santricity/sm-storage/how-do-application-specific-workloads-help-me-manage-my-storage-array.html
Characteristics such as I/O type, segment size, controller ownership, and read and write cache are included in the volume configuration._

After verifying this and trying to create a volume in a lab environment, I found almost no difference among the various workloads, which led me to ask this question. The only change I could see was in ownership
Are there any conditions under which a parameter would be adjusted or not adjusted? 
Also, it doesn't appear that there's anything relevant in the visible sections, what kind of parameter is 'I/O type'?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Thank you so much for your feedback. We'll take at the issue and update and the documentation accordingly. If you have any other feedback, please let us know.

Thanks again, 

Don Riley

**Comment by netapp-driley** [comment]
Following up on this item, content related to default system configurations for workloads will be removed from the documentation and published as soon as possible.
