### ISSUE TITLE
 Expansion volume capacity does not affect performance if the volume in the disk pool

### ISSUE THREAD

**Issue by u02858374725** [NetAppDocs/e-series-santricity#28]
### Page URL

https://docs.netapp.com/us-en/e-series-santricity/sm-storage/increase-capacity-of-a-volume.html

### Page title

Increase capacity of a volume

### Summary

The following description applies only to volumes in the volume group. Since it does not match the behavior of volumes in the disk pool, please clarify the differences between them.

> Select Home > View Operations in Progress to view the progress of the increase capacity operation that is currently running for the selected volume. This operation can be lengthy and could affect system performance.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Thank you so much for your feedback. We will review this item and update the documentation accordingly. If you have any other feedback, please let us know. 

Thanks again, 

Don Riley

**Comment by netapp-driley** [comment]
Thanks again for your feedback. I was able to verify with the E-Series team that the existing content does apply for most disk pool expansion use cases. Basically, an IAF operation is performed when expanding most pools, which can affect performance. The exception being pools with Resource Provisioning, a feature available only on EF300 and EF600 controllers. 

For your reference, here is the official response from the E-Series engineering team:

> In the case of a legacy VG, expanding any volume except the “last one” forces us to physically move the data of all of the volume that cover after the one being expanded to make room.  This is the operation that can effect system performance.  With a pool, we merely allocate some more CSrtripes to the volume and there is no data movement involved.
> 
> If the pool having a volume expanded is not Resource Provisioned (only available on EF300/EF600 with NVMe drives) then the expanded portion of the volume will have an IAF operation.  It is possible for IAF to effect system performance, but probably not to the extent of the data movement of volume expansion for a legacy VG.

**Comment by u02858374725** [comment]
Thanks for the confirmation and sharing details. I will see the updated description.
