### ISSUE TITLE
E-series syslog statement does not hold up

### ISSUE THREAD

**Issue by sndstone** [NetAppDocs/e-series-santricity#5]
Page: [Configure syslog server for alerts](https://docs.netapp.com/us-en/e-series-santricity/sm-settings/configure-syslog-server-for-alerts.html) and https://docs.netapp.com/us-en/e-series-santricity-115/sm-settings/configure-syslog-server-for-alerts.html Say "|The event monitor sends alerts to the syslog server whenever an alertable event occurs" but the MEL (major event log) is not send over syslog. This needs to be done by API requests since the syslog does only include some audit events but not MEL.

**Comment by netapp-jsnyder** [comment]
Thanks @sndstone. We will take a look and make any necessary corrections.

**Comment by netapp-jolieg** [comment]
Here is the response from our Dev team -- (we will make the recommended update by adding cross-refs)

There are two separate syslog settings. One is for alerts (Settings -> Alerts -> Syslog) and the other is for audit logs (Settings -> Access Management -> Audit Log -> Configure Syslog Servers). When the alerts syslog settings are configured, the storage array will send alertable events (MEL events marked with the alertable flag) to the configured syslog servers. When the audit log syslog settings are configured, the storage array will send all audit log entries to the configured syslog servers. It sounds like the person submitting the GitHub comment has the audit log syslog settings configured but not the alerts syslog settings. I think the online help is describing the feature accurately but perhaps it would be helpful to provide some links from one to the other so people know there are multiple syslog settings that can be configured.
