### ISSUE TITLE
Update content of "Change a thin volume to a thick volume"

### ISSUE THREAD

**Issue by ahmadm-netapp** [NetAppDocs/e-series-santricity#6]
Page: [Copy Volume overview](https://docs.netapp.com/us-en/e-series-santricity/sm-storage/copy-volume-function.html)

Recently, a question came up from one of the partners regarding the thin volume capacity used to check when finding an appropriate target volume. Thin volumes have two capacities: 

(1) Virtual Capacity (aka Reported Capacity in SAM)
(2) Repository Capacity (aka Allocated  Capacity in SAM)

The answer is Virtual Capacity. Allocated capacity is normally much smaller than virtual capacity so we should clearly state that in here. The target volume must have a capacity equal or larger to the thin volume reported capacity (virtual capacity).

**Comment by netapp-jolieg** [comment]
OK, thanks. I will put this on our to-do list for Raptor.

**Comment by netapp-driley** [comment]
This correction will be available in the next published release of the documentation.
